NIX_PROFILE=$HOME/.nix-profile

# Powerline
POWERLINE_MODUES="venv,user,ssh,cwd,nix-shell,perms,git,jobs,exit,root"
POWERLINE_OPTIONS="-cwd-mode dironly -max-width 60"
POWERLINE_PRIORITY="root,user,host,ssh,perms,git-branch,git-status,cwd,hg,jobs,exit,cwd-path"

function _update_ps1() {
    PS1="$($NIX_PROFILE/bin/powerline-go -jobs $(jobs -p | wc -l) -modules $POWERLINE_MODUES -priority $POWERLINE_PRIORITY $POWERLINE_OPTIONS)"
}

if [ "$TERM" != "linux" ] && [ -f "$NIX_PROFILE/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

# Bat
export BAT_THEME="Solarized (dark)"

# Godot
[ -f $HOME/Library/Application\ Support/Steam/steamapps/common/Godot\ Engine/Godot.app/Contents/MacOS/Godot ] && alias godot="$HOME/Library/Application\ Support/Steam/steamapps/common/Godot\ Engine/Godot.app/Contents/MacOS/Godot"
[ -f $HOME/Library/Application\ Support/Steam/steamapps/common/Godot\ Engine/Godot.app/Contents/MacOS/Godot ] && alias gut='godot --debug-collisions --path $PWD -d -s addons/gut/gut_cmdln.gd'

# Completion
set show-all-if-ambiguous on
bind 'TAB:menu-complete'
bind '"\e[Z":complete'

# Nix
# FIXME: Not work correctly for now
[ -f $NIX_PROFILE/share/nix-direnv/direnvrc ] && source $NIX_PROFILE/share/nix-direnv/direnvrc
[ -f $NIX_PROFILE/bin/direnv ] && eval "$(direnv hook bash)"

# Aliases
alias be="bundle exec"

export EDITOR=vim

# Devbox as package manager
eval "$(devbox global shellenv --init-hook)"
