NIX_PROFILE=$HOME/.nix-profile

# Powerline
POWERLINE_MODUES="venv,user,ssh,cwd,perms,git,jobs,exit,root,direnv,nix-shell"
POWERLINE_OPTIONS="-cwd-mode dironly"

function _update_ps1() {
    PS1="$($NIX_PROFILE/bin/powerline-go -jobs $(jobs -p | wc -l) -modules $POWERLINE_MODUES $POWERLINE_OPTIONS)"
}

if [ "$TERM" != "linux" ] && [ -f "$NIX_PROFILE/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

# Completion
set show-all-if-ambiguous on
bind 'TAB:menu-complete'
bind '"\e[Z":complete'

# Nix
# FIXME: Not work correctly for now
[ -f $NIX_PROFILE/share/nix-direnv/direnvrc ] && source $NIX_PROFILE/share/nix-direnv/direnvrc
[ -f $NIX_PROFILE/bin/direnv ] && eval "$(direnv hook bash)"
