NIX_PROFILE=$HOME/.nix-profile

# Powerline
POWERLINE_MODUES="venv,user,ssh,cwd,nix-shell,perms,git,jobs,exit,root"
POWERLINE_PRIORITY="root,user,host,ssh,perms,git-branch,git-status,cwd,hg,jobs,exit,cwd-path"

function powerline_precmd() {
  PS1="$($NIX_PROFILE/bin/powerline-go -jobs ${${(%):%j}:-0} -modules $POWERLINE_MODUES -priority $POWERLINE_PRIORITY -cwd-mode dironly -max-width 60)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ] && [ -f "$NIX_PROFILE/bin/powerline-go" ]; then
    install_powerline_precmd
fi

# Bat
export BAT_THEME="Solarized (dark)"

# GPG Config
export GPG_TTY=$(tty)

# Restore Key Binding
bindkey -e

# Zsh Extension
[ -f $NIX_PROFILE/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source $NIX_PROFILE/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=10"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)


# Development
[ ! -d $HOME/.pnpm ] && mkdir -p $HOME/.pnpm
export PNPM_HOME=$HOME/.pnpm

[ $(command -v rbenv) ] && eval "$(rbenv init -)"
[ $(command -v go) ] && export PATH=$PATH:$(go env GOPATH)/bin
[ $(command -v yarn) ] && export PATH=$PATH:$(yarn global bin)
[ $(command -v pnpm) ] && export PATH=$PATH:$PNPM_HOME
[ $(command -v cargo) ] && export PATH=$HOME/.cargo/bin:$PATH

[ -f /opt/homebrew/lib ] && export LIBRARY_PATH=/opt/homebrew/lib:$LIBRARY_PATH
export PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:~/.nix-profile/lib/pkgconfig:$PKG_CONFIG_PATH



# Godot
[ -f $HOME/Library/Application\ Support/Steam/steamapps/common/Godot\ Engine/Godot.app/Contents/MacOS/Godot ] && alias godot="$HOME/Library/Application\ Support/Steam/steamapps/common/Godot\ Engine/Godot.app/Contents/MacOS/Godot"
[ -f $HOME/Library/Application\ Support/Steam/steamapps/common/Godot\ Engine/Godot.app/Contents/MacOS/Godot ] && alias gut='godot --debug-collisions --path $PWD -d -s addons/gut/gut_cmdln.gd'

# Nix
[ -f $NIX_PROFILE/share/nix-direnv/direnvrc ] && source $NIX_PROFILE/share/nix-direnv/direnvrc
[ -f $NIX_PROFILE/bin/direnv ] && eval "$(direnv hook zsh)"

# Auto Complection
fpath=($NIX_PROFILE/share/zsh/site-functions $fpath)
[ -f $NIX_PROFILE/share/git/contrib/completion/git-completion.zsh ] && zstyle ':completion:*:*:git:*' script $NIX_PROFILE/share/git/contrib/completion/git-completion.zsh

autoload -Uz compinit && compinit

# History
setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY

# Alias
alias be="bundle exec"
alias rake='noglob rake'

export EDITOR=vim
export GPG_TTY=$(tty)

# Devbox as package manager
eval "$(devbox global shellenv --init-hook)"
